# -*- coding: utf-8 -*-
"""ProfileScraper.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vWCk4QcYzbsQ1Y3mdw2hs1qiZtP1Vddo
"""

from googlesearch import search

def get_profile(keyword):
  results = list(search(keyword, stop=5))
  results = results[:][:]
  facebook_profile_link, twitter_profile_link, linkedin_profile_link = '','',''
  profiles = {
      'twitter': '',
      'facebook': '',
      'linkedin':''
  }
  for r in results:
    if r.find('twitter') != -1 and profiles['twitter'] == '':
      r = r.replace('https://twitter.com/','')
      if r.find('?') != -1:
        r = r[:r.find('?')]
      profiles['twitter'] = r
    if r.find('facebook') != -1 and profiles['facebook'] == '':
      r = r.replace('https://www.facebook.com/','')
      profiles['facebook'] = r
    if r.find('linkedin') != -1 and profiles['linkedin'] == '':
      r = r.replace('https://in.linkedin.com/in/','')
      profiles['linkedin'] = r
  return profiles